version: "3.8"
services:
  slim_app:
    container_name: slim_app
    extra_hosts:
     - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/var/www/html
    depends_on:
      - slim_db

  slim_nginx:
    container_name: slim_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - slim_app
    volumes:
      - ./public:/var/www/html/public

  slim_db:
    container_name: slim_db
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: 'slim'
        MYSQL_USER: 'slim'
        MYSQL_PASSWORD: 'slim'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db-data:/var/lib/mysql 
           
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
